// <auto-generated />
using BaiTap_MVC.Models;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

#nullable disable

namespace BaiTap_MVC.Migrations
{
    [DbContext(typeof(AppDbContext))]
    [Migration("20260420144752_Init")]
    partial class Init
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "9.0.7")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder);

            modelBuilder.Entity("BaiTap_MVC.Models.DangKyHoc", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<int>("LopHocPhanId")
                        .HasColumnType("int");

                    b.Property<int>("SinhVienId")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.HasIndex("LopHocPhanId");

                    b.HasIndex("SinhVienId");

                    b.ToTable("DangKyHocs");
                });

            modelBuilder.Entity("BaiTap_MVC.Models.GiaoVien", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("HoTen")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Id");

                    b.ToTable("GiaoViens");
                });

            modelBuilder.Entity("BaiTap_MVC.Models.KhoaHoc", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("TenKhoaHoc")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Id");

                    b.ToTable("KhoaHocs");
                });

            modelBuilder.Entity("BaiTap_MVC.Models.LopHocPhan", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<int>("GiaoVienId")
                        .HasColumnType("int");

                    b.Property<int>("KhoaHocId")
                        .HasColumnType("int");

                    b.Property<string>("TenLopHocPhan")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Id");

                    b.HasIndex("GiaoVienId");

                    b.HasIndex("KhoaHocId");

                    b.ToTable("LopHocPhans");
                });

            modelBuilder.Entity("BaiTap_MVC.Models.SinhVien", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("HoTen")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("Tuoi")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.ToTable("SinhViens");
                });

            modelBuilder.Entity("BaiTap_MVC.Models.DangKyHoc", b =>
                {
                    b.HasOne("BaiTap_MVC.Models.LopHocPhan", "LopHocPhan")
                        .WithMany("DangKyHocs")
                        .HasForeignKey("LopHocPhanId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("BaiTap_MVC.Models.SinhVien", "SinhVien")
                        .WithMany("DangKyHocs")
                        .HasForeignKey("SinhVienId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("LopHocPhan");

                    b.Navigation("SinhVien");
                });

            modelBuilder.Entity("BaiTap_MVC.Models.LopHocPhan", b =>
                {
                    b.HasOne("BaiTap_MVC.Models.GiaoVien", "GiaoVien")
                        .WithMany("LopHocPhans")
                        .HasForeignKey("GiaoVienId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("BaiTap_MVC.Models.KhoaHoc", "KhoaHoc")
                        .WithMany("LopHocPhans")
                        .HasForeignKey("KhoaHocId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("GiaoVien");

                    b.Navigation("KhoaHoc");
                });

            modelBuilder.Entity("BaiTap_MVC.Models.GiaoVien", b =>
                {
                    b.Navigation("LopHocPhans");
                });

            modelBuilder.Entity("BaiTap_MVC.Models.KhoaHoc", b =>
                {
                    b.Navigation("LopHocPhans");
                });

            modelBuilder.Entity("BaiTap_MVC.Models.LopHocPhan", b =>
                {
                    b.Navigation("DangKyHocs");
                });

            modelBuilder.Entity("BaiTap_MVC.Models.SinhVien", b =>
                {
                    b.Navigation("DangKyHocs");
                });
#pragma warning restore 612, 618
        }
    }
}
